### ISSUE TITLE
QPropertyAnimation: you're trying to animate a non-existing property opacity of your QObject

### ISSUE THREAD

**Issue by ByteMastermind** [yjg30737/pyqt-toast#1]
`QPropertyAnimation: you're trying to animate a non-existing property opacity of your QObject`

This error pops up after displaying the toast. However, the fade-out animation is still visible .

**Comment by yjg30737** [comment]
Thanks. I've just found out why that happened and fix that

# Incorrect

```python
self.__animation = QPropertyAnimation(self, b"opacity")
```

# Correct 

```python
self.__animation = QPropertyAnimation(self, b"windowOpacity")
```

**Comment by ByteMastermind** [comment]
Thanks, that solves the issue.
